name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: false
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run ci

  test:
    runs-on: [ubuntu-latest]
    needs: lint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: false
      - run: pnpm install
      - run: pnpm test
